[add] #88 public/private filter
Kyutech-C3/toybox-server pull request #101
Opened 2022-07-10 08:37 UTC by yamato0211

#88 public/privateのフィルターの追加

2022-07-12 01:06 UTC, PigeonsHouse requested changes

2022-07-12 01:06 UTC, PigeonsHouse commented on routers/works/__init__.py
> +async def get_works(limit: int = 30, visibility: str = None, oldest_id: str = None, db: Session = Depends(get_db), user: User = Depends(GetCurrentUser(auto_error=False))):
ここも`visibility`の型を`models.Visibility`に修正しておいてください．

2022-07-12 01:07 UTC, PigeonsHouse commented
フォーマッタによる修正がこのブランチに入ってしまうと今出てるMRのブランチがコンフリクトしかねないので一旦全部閉じた後リファクタブランチなどを用意して対応したいと考えています．そのため，フォーマッタの修正を切り戻してくれるとありがたいです．

2022-07-14 10:12 UTC, yamato0211 commented
フォーマッタってvscode保存時にフォーマットしてくれるやつですか？

2022-07-16 13:08 UTC, PigeonsHouse commented
> フォーマッタってvscode保存時にフォーマットしてくれるやつですか？

そです．保存時の自動フォーマッタを切ってフォーマットされてる箇所を[**ここ**](https://github.com/Kyutech-C3/toybox-server/pull/101/files)とか見ながら切り戻してほしいです．めっちゃダルいと思うけど()

2022-07-19 00:19 UTC, PigeonsHouse approved these changes
OKです！！

2022-07-19 00:19 UTC, merged