Feature/forword match tag
Kyutech-C3/toybox-server pull request #106
Opened 2022-08-13 11:41 UTC by Simo-C3

2022-08-14 13:47 UTC, PigeonsHouse requested changes

2022-08-14 13:47 UTC, PigeonsHouse commented on routers/tags/tag.py
> +    tag_list = get_tags(db, limit, w)
wだと何の変数かわかりにくく可読性が下がるので何を指す変数かわかりやすい変数名を付けたほうが良いかと思います．(search_strが望ましい？)

2022-08-14 13:47 UTC, PigeonsHouse commented on cruds/tags/tag.py
> +def get_tags(db: Session, limit: int, search_str: str) -> List[GetTag]:
私が把握できていないだけなら申しわけないんですけど，offset_idを消すように判断した理由を知りたいです．

2022-08-14 14:22 UTC, Simo-C3 commented on routers/tags/tag.py
> +    tag_list = get_tags(db, limit, w)
エンドポイントのクエリパラメータのパラメータ名が`?search_str=`よりも`?w=`の方が簡潔でキレだと思って'w'にしています。

2022-08-14 14:23 UTC, Simo-C3 commented on cruds/tags/tag.py
> +def get_tags(db: Session, limit: int, search_str: str) -> List[GetTag]:
タグにページング機能は必要ないと判断したからです。

2022-08-15 07:32 UTC, PigeonsHouse commented on routers/tags/tag.py
> +    tag_list = get_tags(db, limit, w)
確かにクエリパラメータは短い方がいいですね．了解しました．

2022-08-15 08:28 UTC, PigeonsHouse commented on cruds/tags/tag.py
> +def get_tags(db: Session, limit: int, search_str: str) -> List[GetTag]:
タグにページング機能が必要ないと判断した理由を確認したいんです．

2022-08-15 13:17 UTC, Simo-C3 commented on cruds/tags/tag.py
> +def get_tags(db: Session, limit: int, search_str: str) -> List[GetTag]:
タグ選択の時に前方一致検索で補完のような感じで表示するだけだからです。例としてはQiitaです

2022-08-16 05:06 UTC, PigeonsHouse commented on cruds/tags/tag.py
> +def get_tags(db: Session, limit: int, search_str: str) -> List[GetTag]:
タグをページングする必要性が十分に低いのはわかりましたが，残したままではいけなかったのでしょうか．
Qiitaのタグ補完のイメージは付きましたが，公式APIドキュメントにはページング機能もあるため用途が雨水にしても消すまではなかったのではないでしょうか．
https://qiita.com/api/v2/docs#get-apiv2tags
ページングを行うことによる危険性や脆弱性がないのであれば残していてもよいかと思います．

2022-08-16 07:32 UTC, rkun123 commented on cruds/tags/tag.py
> +def get_tags(db: Session, limit: int, search_str: str) -> List[GetTag]:
フロントで使わなければよいだけというのはあるし、このcrudsのメソッドは汎用的なやつだから残しておいてもよいとおもう

2022-08-16 07:33 UTC, Simo-C3 commented on cruds/tags/tag.py
> +def get_tags(db: Session, limit: int, search_str: str) -> List[GetTag]:
残す必要もないですけど、消さない理由も一理あるんで一旦残しておきます。ただ、タグにおいて現状のページング（作成日の基準）だと使うにしても微妙なので、別のissueで対応が必要かと

2022-08-16 07:37 UTC, PigeonsHouse approved these changes

2022-08-16 07:37 UTC, PigeonsHouse commented on cruds/tags/tag.py
> +def get_tags(db: Session, limit: int, search_str: str) -> List[GetTag]:
確認しました．

2022-08-16 07:38 UTC, merged