[add] assetのwasabiへのアップロード実装
Kyutech-C3/toybox-server pull request #112
Opened 2022-10-03 13:03 UTC by Simo-C3

2022-10-08 11:58 UTC, PigeonsHouse requested changes

2022-10-08 11:58 UTC, PigeonsHouse commented on Dockerfile
> +RUN pipenv install boto3
改行入れてね

2022-10-10 09:32 UTC, PigeonsHouse commented
`.env.sample`の更新もお願いします

2022-10-10 22:04 UTC, PigeonsHouse commented
変更点内のprintは削除しておいてください．

2022-10-10 22:06 UTC, PigeonsHouse requested changes

2022-10-10 22:06 UTC, PigeonsHouse commented on cruds/assets/__init__.py
> +    print(response)
挙動の確認ができたらprintは削除しておいてください

2022-10-10 22:06 UTC, PigeonsHouse commented on cruds/assets/__init__.py
> +    print(file_url)
挙動の確認ができたらprintは削除しておいてください

2022-10-10 22:24 UTC, PigeonsHouse commented
あとこれは確認なんですが，ローカルの開発環境も同じWasabiの接続情報使って良いんですかね？

2022-10-11 03:41 UTC, Simo-C3 commented
> あとこれは確認なんですが，ローカルの開発環境も同じWasabiの接続情報使って良いんですかね？

今同じの使ってるけど、別な方がいい気がするな。testのときだけ別のenvファイル使うってできるんかな？

2022-10-13 09:19 UTC, Simo-C3 commented
テストの時に環境変数を上書きするようにして対応した

2022-10-13 10:00 UTC, PigeonsHouse approved these changes

2022-10-13 10:03 UTC, merged

2022-10-13 10:19 UTC, rkun123 commented on cruds/assets/__init__.py
> +
[COMMENT]
将来wasabiへのファイルアップロードをする場面が増えてきたら、boto3クライアントは使いまわしたいっすね

`get_boto3_client()`みたいな関数を別の場所で定義しておいて取得する
dbみたいに引数で受け取るようにして、router側で`get_boto3_client()`して渡す
のどちらかが良いかも。
（さらに、クライアントを抽象化するクラスを作って、テストのときにモック化できるようにできるとさらに理想かもです）
といいつつここはリリース後とかで大丈夫そうです👍