Fix/user icon
Kyutech-C3/toybox-server pull request #132
Opened 2023-04-15 13:24 UTC by PigeonsHouse

2023-04-15 13:25 UTC, PigeonsHouse commented
新規テストの追加がまだです

2023-04-19 08:07 UTC, PigeonsHouse commented
@Simo-C3 
テスト書いたのでレビューお願いします

2023-05-03 12:38 UTC, Simo-C3 requested changes

2023-05-03 12:38 UTC, Simo-C3 commented on cruds/users/auth.py
> +            upload_avatar(file_bin)
エラー処理もやった方がいいです

2023-05-10 09:25 UTC, Simo-C3 requested changes

2023-05-10 09:25 UTC, Simo-C3 commented on routers/users/__init__.py
> +    if user.avatar_url:
アバターの削除処理は新しいアバター画像の投稿に成功して、ユーザー情報の更新を行なった後にした方がいいです

2023-05-10 10:14 UTC, PigeonsHouse commented on routers/users/__init__.py
> +    if user.avatar_url:
あー、この順の理由は、拡張子が一致したファイルを投げると上書きしちゃうから旧origin.pngを削除して新しいorigin.pngを投稿するみたいな意図だね
それはそれとして今の順でもまずいんだけど

2023-05-13 15:11 UTC, Simo-C3 commented on routers/users/__init__.py
> +    if user.avatar_url:
この場合なら上書きしちゃっていいも気もする
上書きしないようにするならそもそもファイル名をoriginとかにするんじゃなくてuidにしていい気がする

2023-05-13 15:13 UTC, Simo-C3 commented
実装へのコメントではないけどアバター画像の投稿時にresize処理せんとフロントの読み込みめっちゃ重くなる気がする
フロントのアバター変更機能実装前に画像関連のresize実装したいな

2023-06-03 15:26 UTC, Simo-C3 requested changes

2023-06-03 15:26 UTC, Simo-C3 commented on utils/wasabi.py
> +        Bucket=S3_BUCKET, Key=f"{S3_DIR}/avatar/{user_id}/origin.{extension}"
deleteのkeyは`{S3_DIR}/avatar/{user_id}.{extension}`です

2023-06-03 15:26 UTC, Simo-C3 commented on utils/convert.py
> +    image.resize((256, 256))
resizeした画像がうまく保存できていないです
`resize=image.resize((256, 256))`にしないといけない気がします

2023-06-03 15:26 UTC, Simo-C3 commented on utils/convert.py
> +    image.resize((256, 256))
あと、この方法でresizeしたら縦横比がずれて元画像が歪んでしまいます
縦横比を保持しながらresizeできるようにしないといけないので、元画像から最大の正方形を切り出して（中央）、そのあとリサイズするようにしたほうがいいと思う。
↓参考
https://note.nkmk.me/python-pillow-square-circle-thumbnail/

2023-06-03 15:26 UTC, Simo-C3 commented on utils/convert.py
> +    image.resize((256, 256))
参考
```python
    image = image.crop(
        (
            (image_width - min(image.size)) // 2,
            (image_height - min(image.size)) // 2,
            (image_width + min(image.size)) // 2,
            (image_height + min(image.size)) // 2,
        )
    )
```

2023-06-03 15:26 UTC, Simo-C3 commented on utils/convert.py
> +    image.resize((256, 256))
`image.save(result_io, format="webp", optimize=True, quality=80)`
qualityを70-80ぐらいで保持して欲しいです

2023-06-03 15:57 UTC, PigeonsHouse commented
対応したんですけど急にローカルでWasabiが繋がらなくなったので、縦横比変更とかクリップのとこらへんがちゃんと動いてるか検証できてないです…
完成はしてますけどWIPくらいのノリでのpushです()

2023-07-10 07:20 UTC, merged