リファクタリング
Kyutech-C3/toybox-server pull request #139
Opened 2023-11-02 15:02 UTC by PigeonsHouse

## 概要
以下の内容でリファクタリングを行いました
- isort, black, flake8, pre-commitの導入
  - circleCIにflake8追加
- ファイル末尾の改行追加、空白行の空白削除
- pyenv用ファイル追加
- 推奨拡張機能にErrorLens追加
- __init__.pyを、そのフォルダ下のファイルのexport用の用途に絞る
  - __init__.pyでimport文のみ書くことで、`from cruds.tags.tag import xxx` みたいなやつを `from cruds.tags` と書けるように変更

2023-11-06 08:34 UTC, Simo-C3 commented
作品に対するコメントを投稿しても、コメント取得した時に何も返ってこなくなってしまってます
原因はわかっていません
同じ現象になるか試してみてください

2023-11-06 08:35 UTC, Simo-C3 requested changes
作品に対するコメントを投稿しても、コメント取得した時に何も返ってこなくなってしまってます
原因はわかっていません
同じ現象になるか試してみてください

2023-11-12 14:01 UTC, PigeonsHouse commented on cruds/comments/comment.py
> +        .filter(models.Comment.reply_at is None)
flake8の指摘でここの`== None`を`is None`に変えたことで挙動が変わってました。
flake8的には`== None`は警告出されるので、`reply_at.is_(None)`に修正しました。
[is_()](https://docs.sqlalchemy.org/en/14/core/sqlelement.html#sqlalchemy.sql.expression.ColumnElement.is_)
また、`is None`をormに含むような同様なミスが無いか上から確認しましたがここのみでした。

2023-11-20 15:04 UTC, Simo-C3 approved these changes
問題ないと思います
お疲れ様です

2023-11-20 15:05 UTC, merged