minioの導入
Kyutech-C3/toybox-server pull request #140
Opened 2023-11-04 07:18 UTC by PigeonsHouse

テスト用にwasabiのmockを立てるため、minioを導入する
refactorのPRがマージされたら、developをrebaseしてからdraftを解除する

2023-11-20 16:36 UTC, PigeonsHouse commented
refactoringブランチがマージされ、CIのエラーも解消し終えたのでready for reviewしました。
余談ですが、CircleCIの設定いじらずにエラー解消できました…申し訳ないですrkun先輩…

2023-11-24 13:10 UTC, Simo-C3 commented
テストだけじゃなくてローカル開発の時に環境変数でdevの時はminioを使うようにしませんか？ちなみにprodの時はwasabiを使う

2023-11-24 13:10 UTC, Simo-C3 requested changes

2023-11-24 13:10 UTC, Simo-C3 commented on utils/wasabi.py
> +        wasabi.put_object(
mime typeを指定するようにしてください

2023-11-24 13:10 UTC, Simo-C3 commented on utils/wasabi.py
> +        wasabi.delete_object(Bucket=S3_BUCKET, Key=f"{S3_DIR}/{asset_type}/{asset_id}")
これでちゃんとオブジェクトって消せる？

2023-11-24 16:17 UTC, PigeonsHouse commented
> テストだけじゃなくてローカル開発の時に環境変数でdevの時はminioを使うようにしませんか？ちなみにprodの時はwasabiを使う

こっちに関してはPRがマージされるのが遅くなると面倒なので別PRで対応していきたいです。
企業が運用するコードとかでもないので精密性もそこまで求められないと思うので、ある程度はがしがしマージして、developブランチが育つペースをあげていきたい気持ちです。

2023-11-24 16:18 UTC, PigeonsHouse commented on utils/wasabi.py
> +        wasabi.delete_object(Bucket=S3_BUCKET, Key=f"{S3_DIR}/{asset_type}/{asset_id}")
ファイル名無いから消えない気がするね…

2023-11-24 16:33 UTC, PigeonsHouse commented on utils/wasabi.py
> +        wasabi.delete_object(Bucket=S3_BUCKET, Key=f"{S3_DIR}/{asset_type}/{asset_id}")
avatarの方もファイル名変えてなかったので合わせて修正しました。

2023-11-24 16:33 UTC, PigeonsHouse commented on utils/wasabi.py
> +        wasabi.put_object(
修正しました

2023-11-27 05:51 UTC, Simo-C3 approved these changes

2023-11-27 05:53 UTC, merged