feat: add v2 work router
Kyutech-C3/toybox-server pull request #141
Opened 2023-11-13 05:55 UTC by tosaken1116

作品取得のAPIを作成しました
testをまだ書いていないのでルーティングから外しています。

2023-11-21 05:55 UTC, PigeonsHouse commented
まだしっかりレビュー出来てないんですが、とりあえずrefactoringブランチをマージしたのでrebase || mergeお願いします

2023-11-24 00:35 UTC, PigeonsHouse requested changes
developブランチにformat, lintの環境が整備されたので、取り込んで修正していただけたら再レビューします。ただ、今の所コメントした所の修正+developの取り込みでapproveにはなるかなと思います。

2023-11-24 00:35 UTC, PigeonsHouse commented on main.py
> +# from routers.v2.router import v2
`routers`の`__init__.py`で`import`して、`from routers import router, v2`みたいにまとめてimportを書きたい

2023-11-24 00:35 UTC, PigeonsHouse commented on main.py
> +# app.include_router(v2, prefix="/api/v2",tags=["v2"])
mainでincludeしてるのは🙆
コメントアウトしてるのは動かなかった感じ？

2023-11-24 00:35 UTC, PigeonsHouse commented on routers/v2/router.py
> +v2 = APIRouter()
ちょっとした命名の話だけど、v2_routerみたいに変数の中がrouterだってわかる命名にしてほしい

2023-11-24 00:35 UTC, PigeonsHouse commented on routers/v2/works/router.py
> +    user: User = Depends(GetCurrentUser(auto_error=False)),
コードの見た目の話ではあるけど、この2個を引数の一番最後に置きたい

2023-11-24 00:35 UTC, PigeonsHouse commented on routers/v2/works/router.py
> +    search_word:str= None
=の前にスペースが入ってないけど、blackのformat働いてる？
format関係のレビューサボりたいのでもし動いてなかったら設定見直してほしいです。

2023-11-24 00:35 UTC, PigeonsHouse commented on routers/v2/works/router.py
> +    search_word:str= None
refactoringをリベース前だから働いてるわけないわな。develop取り込んだら設定お願いします～

2023-11-24 00:35 UTC, PigeonsHouse commented on cruds/v2/works/get.py
> +    print(len(works))
挙動確認終わったら削除お願いします

2023-11-24 00:35 UTC, PigeonsHouse commented on cruds/v2/works/get.py
crudsはrouters依存の存在にしたくないのでcrudsにはv2の概念を持ち込まず、cruds/worksの中に関数追加、もしくは既存の関数の改造を行ってそれをv2のrouterで使うような方針でお願いしたいです。

2023-11-24 13:51 UTC, tosaken1116 commented on main.py
> +# app.include_router(v2, prefix="/api/v2",tags=["v2"])
コメントアウトしてるのはテストを書いてないので本番実装で運用されないように一時的にコメントアウトしてるだけです！

2023-11-24 13:56 UTC, tosaken1116 commented on cruds/v2/works/get.py
既存の関数の改造を行うとv1がdeprecateになる間もなく廃止する必要性が出てくるため新規関数として追加します

2023-11-24 14:34 UTC, PigeonsHouse commented
test書いたらapprovedします！

2023-11-24 16:00 UTC, PigeonsHouse approved these changes

2023-11-24 16:00 UTC, PigeonsHouse commented on tests/test_work.py
test失敗したときに原因の切り分けしなきゃなのでテストケースは追記じゃなくて新規作成してください。
1エンドポイントで複数テストケース分ける勢いで！(1エンドポイント1個でも可)
とりあえず追記分を新規のテストに分けてくれればapproveします～

2023-11-29 02:01 UTC, merged